- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/PHPCR/Query/Builder/BuilderConverterPhpcr.php
- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/BuilderConverterPhpcrTest.php
This method is called by doctrine-extension for ORM and Mongo ODM but for some reason it's missing in PHPCR
> Added getFieldMapping method

- lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/AttributeTranslationStrategy.php
- tests/Doctrine/Tests/Models/Translation/Article.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/Translation/AttributeTranslationStrategyTest.php
Follow up to: https://github.com/doctrine/phpcr-odm/pull/602
I wonder what else I missed, maybe "assoc" fields. Will add some better tests in this PR.
> Read translated custom property name

- lib/Doctrine/ODM/PHPCR/Event.php
- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/EventComputingTest.php
Added yet another event.
Use case: We have a content serializer which serializes dynamic content data to multiple nodes, when the translation is bound we need to store the current content, and later resetore it in loadTranslation.
This event overlaps with the `preCreateTranslation` event, which is only called when the translation is created, this information could be passed in the `loadTranslation` event.
> Added preBind translation

- CHANGELOG.md
- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadataFactory.php
- lib/Doctrine/ODM/PHPCR/Mapping/MappingException.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataFactoryTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/UuidMappingObjectNotReferenceable.php
jackalope started to verify that the uuid is not set on a non-referenceable node, [leading to confusion](https://github.com/jackalope/jackalope/issues/281) when people map the uuid but do not make the document referenceable.
> Verify that uuid is only mapped on referenceable documents

- CHANGELOG.md
- lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/AbstractTranslationStrategy.php
- lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/AttributeTranslationStrategy.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/Translation/AttributeTranslationStrategyTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Translation/AttributeTranslationStrategyTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Translation/LocaleChooserTest.php
It seems that locales such as `de_at` are not included when `->getLocalesFor` is called.
> Allow sub localizations

- .travis.yml
- CHANGELOG.md
- composer.json
- lib/Doctrine/ODM/PHPCR/Decorator/DocumentManagerDecorator.php
- lib/Doctrine/ODM/PHPCR/DocumentManagerInterface.php
fix bugs revealed in #655 
we seem to miss a mess detector check to tell when the interface and an implementation do not match.
> fixing DocumentManagerInterface

- lib/Doctrine/ODM/PHPCR/Query/Builder/QueryBuilder.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/QueryBuilderTest.php
Deep clone converter dependency on QueryBuilder, so constraints are reset when cloning a QueryBuilder instance.
Fixed issue https://github.com/Sylius/Sylius/issues/3752
> Fix QueryBuilder cloning issue (deep clone converter dependency)

- .styleci.yml
we should ignore the classes that are not legal on PHP 7. they must simply not be autoloaded in PHP 7.
> fix styleci

- doctrine-phpcr-odm-mapping.xsd
- lib/Doctrine/ODM/PHPCR/ReferenceManyCollection.php
- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
- tests/Doctrine/Tests/Models/References/RefManyTestObjPathStrategy.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/ReferenceTest.php
Based on suggestion in #687 I added parameter referenceType to ReferenceManyCollection 
so that nodes can be loaded either from a list of uuids or from a list of paths.
The test is in ReferenceTest::testReferenceManyPath, I had to call $referrer->references->refresh(); to invoke the failing behavior.
> Fix for #687 - loading nodes in referencemanycollection with path strategy

- tests/Doctrine/Tests/ODM/PHPCR/DocumentManagerTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Id/RepositoryIdGeneratorTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataFactoryTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/ConverterPhpcrTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/QueryBuilderTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/QueryTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Tools/Command/DocumentConvertTranslationCommandTest.php
- tests/Doctrine/Tests/ODM/PHPCR/UnitOfWorkTest.php
Do not use the deprecated `getMock` method.
Fixes #709
> Use getMockBuilder instead of getMock

- CHANGELOG.md
- composer.json
- doctrine-phpcr-odm-mapping.xsd
- lib/Doctrine/ODM/PHPCR/Mapping/Annotations/Document.php
- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadata.php
- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadataFactory.php
- lib/Doctrine/ODM/PHPCR/Mapping/Driver/AnnotationDriver.php
- lib/Doctrine/ODM/PHPCR/Mapping/Driver/XmlDriver.php
- lib/Doctrine/ODM/PHPCR/Mapping/Driver/YamlDriver.php
- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
- tests/Doctrine/Tests/Models/CMS/CmsArticleFolder.php
- tests/Doctrine/Tests/Models/CMS/CmsBlogFolder.php
- tests/Doctrine/Tests/Models/CMS/CmsBlogInvalidChild.php
- tests/Doctrine/Tests/Models/CMS/CmsBlogPost.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/UnitOfWorkTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataFactoryTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/ChildClassesAndLeafObject.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/ChildClassesObject.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/IsLeafObject.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/xml/Doctrine.Tests.ODM.PHPCR.Mapping.Model.ChildClassesObject.dcm.xml
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/xml/Doctrine.Tests.ODM.PHPCR.Mapping.Model.IsLeafObject.dcm.xml
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/yml/Doctrine.Tests.ODM.PHPCR.Mapping.Model.ChildClassesObject.dcm.yml
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/Model/yml/Doctrine.Tests.ODM.PHPCR.Mapping.Model.IsLeafObject.dcm.yml
- tests/Doctrine/Tests/ODM/PHPCR/UnitOfWorkTest.php
**TODO**
Doc PR: https://github.com/doctrine/phpcr-odm-documentation/pull/81
This PR allows the restriction of child document types:
```php
/**
* @PHPCRODM\Document(restrictChildren={
*   "Doctrine\Tests\Models\CMS\CmsArticle"
* })
*/
class ArticleFolder
{
// ...
}
```
- By default children are unrestricted (`childRestrictions = null`)
- Children validated on "insert".
- Children validated on "move".
- Ensure structural integrity where it matters.
- Determine which types can be added to a document (e.g. in a tree browser).
- Ultimately this could also be part of the node type definition if we ever implementing that.
We could also implement this as a separate annotation:
```php
/**
* @Document()
* @RestrictChildren({
*   "AppBundle\Document\Foo"
*   "AppBundle\Document\Bar"
* }, …
```
> Support child restriction

- lib/Doctrine/ODM/PHPCR/NodeTypeRegistrator.php
- lib/Doctrine/ODM/PHPCR/Tools/Console/Command/RegisterSystemNodeTypesCommand.php
Fixes #712 
This is a quick fix to decouple the registration of system types from the console command.
> Register system node types in dedicated class

- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadata.php
Some slow moving vendor dependencies (like JMS Serializer, ref
schmittjoh/serializer#605) hold up the development at the moment. Keeping
this method for the moment will fix it.
This PR should be reverted before 2.0.0 is released.
> Temporary revert getField() removal

- README.md
Use the master branch for the travis badge.
> Use master branch for travis branch

- tests/Doctrine/Tests/ODM/PHPCR/Mapping/AnnotationDriverTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataFactoryTest.php
`AnnotationReader` constructor for `doctrine/annotations` >=1.3: `public function __construct(DocParser $parser = null)`
`AnnotationReader` constructor for `doctrine/annotations` <1.2: `public function __construct()`
No idea why cache was injected there in the tests 🎉
> Make tests compatibile with doctrine/annotations 1.3

- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
When persisting a new document with children, the children are automatically persisted as well. However, this persistence of the children is done using an override ID generator (assigned). This means the children are required to have an `@Id` field in order to be persisted.
I don't know why this is done and it didn't work as expected when working with the PHPCR ODM (I don't want to use the assigned ID strategy).
The line is added in https://github.com/doctrine/phpcr-odm/pull/50 . Unfortunately, the related issue can no longer be read as Jira is removed. However, the tests all still pass, so I don't think I've broken the fix.
Again, I'm not an PHPCR ODM expert and don't know if there was a specific reason to do this, but using the one from the ClassMetadata makes a lot more sense in my …
> Don't override ID generator when persisting children

- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
The assignment was using the object id of the parent, instead of the child.
> Fix updating new Id for children after a move.

- .travis.yml
travis moved to the trusty distribution which does not provide the ancient php 5.3 version anymore.
> fix php 5.3 build

- .travis.yml
- README.md
- composer.json
reduced to only drop 5.x and 7.0 support and add 7.1 testing. adding php 7.2 support is blocked by the dependencies needing to support it first. will be done in a separate PR.
> drop php 5 support for version 2

- composer.json
- tests/Doctrine/Tests/ODM/PHPCR/DocumentClassMapperTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Event/MoveEventArgsTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Id/AssignedIdGeneratorTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Id/IdGeneratorTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Id/ParentIdGeneratorTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Id/RepositoryIdGeneratorTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/AbstractMappingDriverTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataFactoryTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataTest.php
- tests/Doctrine/Tests/ODM/PHPCR/PHPCRFunctionalTestCase.php
- tests/Doctrine/Tests/ODM/PHPCR/PHPCRTestCase.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/AbstractLeafNodeTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/AbstractNodeTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/ConverterPhpcrTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/LeafNodeTestCase.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/Builder/NodeTestCase.php
- tests/Doctrine/Tests/ODM/PHPCR/Query/QueryTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Tools/Command/DocumentConvertTranslationCommandTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Tools/Command/DumpQueryBuilderReferenceCommandTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Tools/Helper/UniqueNodeTypeHelperTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Tools/Test/QueryBuilderTesterTest.php
Use [PSR-1](http://www.php-fig.org/psr/psr-1/#namespace-and-class-names) while extending PHPUnit TestCase class. This will help us when to migrate to PHPUnit 6, that [no longer support snake case namespaces](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
> Use PSR-1 for PHPUnit TestCase

- benchmarks/PersistBench.php
- lib/Doctrine/ODM/PHPCR/Id/IdException.php
- tests/Doctrine/Tests/Models/CMS/CmsBlogInvalidChild.php
- tests/Doctrine/Tests/Models/CMS/CmsBlogPost.php
- tests/Doctrine/Tests/Models/References/ParentNoNodenameTestObj.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/UnitOfWorkTest.php
fix #737, fix #739
i prefer to go with consistent Nodename over potentially doing a BC break for people on systems that are case sensitive with these. that way it will continue to work but we avoid confusion.
> be sure to have Nodename annotation consistently lowercase

- .styleci.yml
- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/BasicCrudTest.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/ReferenceTest.php
`unset` allow us to pass multiple values to check.
[PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me on that.
Also enabled in [`StyleCI`](https://styleci.readme.io/docs/fixers#section-combine_consecutive_iunsets).
> Combine consecutive unsets

- docs/en/reference/architecture.rst
Points to latest version of the docs. Better that than a specific version that'll be outdated in the future.
The user will be shown the version number and will be warned anyway if the version is not yet released or too old.
> Add link to doctrine 2 architecture in the documentation

- lib/Doctrine/ODM/PHPCR/DocumentManager.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/Translation/DocumentManagerTest.php
I'm not entirely sure why it's the document manager findMany is failing here, but the following scenario fails:
I have a `project.category` and a `category.projects`, where `category.projects` is a referrer to a project document referenced by its `category` field and category and project both have translatable fields.
when u then write the following query:
```php
$queryBuilder->fromDocument(ProjectCategory::class, 'pc');
$join = $queryBuilder->addJoinInner();
$join->right()->document(Project::class, 'p');
$join->condition()->equi('p.category', 'pc.projects');
```
It will return all categories, but without translations mapped to it
> fix translations missing when using the query builder with joins on referrer fields

- lib/Doctrine/ODM/PHPCR/UnitOfWork.php
- tests/Doctrine/Tests/Models/References/ParentWithChildrenTestObj.php
- tests/Doctrine/Tests/ODM/PHPCR/Functional/UnitOfWorkTest.php
Hi @dbu ,
I discovered a critical bug that has plagued our application and it took me a while to figure out what was happening, the hardest part was trying to reproduce it in a test because I could see it going wrong, just didn't know why in out app and not in my test case. It needed multiple conditions to be true before it happened:
- fetch a parent node and iterate through its children
- update one of these children their nodename
- have a preUpdate listener present (as uow only triggers another changeset in this case)
in this case in runts through changeset 2se the first time everything goes as expected, and then updates the parents collection with the new child name and marks it moved (a move is also scheduled), but then the second time (after preUpdate) changeset is requested and the …
> fix children getting removed on move when pre update listener is present

- lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadataFactory.php
The backslash is incompatible with PSR-16 cache adapters and after moving from doctrine/cache to symfony/cache this triggers an error.
> Make cache salt compatible with PSR-16
