lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadataFactory.php

The depth mapping is not being inherited ...

Fixed depth inheritance

---

CHANGELOG.md
lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/AttributeTranslationStrategy.php
lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/ChildTranslationStrategy.php
lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/TranslationStrategyInterface.php

fix #613 for queries with join from is a source

---

lib/Doctrine/ODM/PHPCR/Query/Builder/AbstractNode.php
lib/Doctrine/ODM/PHPCR/Query/Builder/BuilderConverterPhpcr.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintDescendant.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintFieldIsset.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintFullTextSearch.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintSame.php
lib/Doctrine/ODM/PHPCR/Query/Builder/OperandDynamicFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/OperandFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/OrderBy.php
lib/Doctrine/ODM/PHPCR/Query/Builder/QueryBuilder.php
lib/Doctrine/ODM/PHPCR/Query/Builder/Select.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceDocument.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceJoin.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceJoinConditionDescendant.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceJoinConditionEqui.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceJoinConditionFactory.php

I noticed that we have some typos in the docs. Went over them and also cleaned other codestyle issues.

cleaning up phpdoc on query builder

---

lib/Doctrine/ODM/PHPCR/UnitOfWork.php
tests/Doctrine/Tests/ODM/PHPCR/UnitOfWorkTest.php
tests/travis_doctrine_dbal.sh

Allow changeset computations of removed documents

---

CHANGELOG.md

Added changelog note for custom translated property mapping fix. Fixes #606

Added CHANGELOG note about translated property

---

.travis.yml
CHANGELOG.md
cli-config.doctrine_dbal.php.dist
cli-config.jackrabbit.php.dist
composer.json
tests/travis_doctrine_dbal.sh
tests/travis_jackrabbit.sh

allow symfony 3 components

---

lib/Doctrine/ODM/PHPCR/Proxy/ProxyFactory.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/ProxyTest.php

fix for https://github.com/doctrine/phpcr-odm/issues/663

Proxy for parent nodename classes

---

CHANGELOG.md
bin/phpcrodm.php
composer.json
lib/Doctrine/ODM/PHPCR/DocumentManager.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConverterBase.php
lib/Doctrine/ODM/PHPCR/Query/Query.php
lib/Doctrine/ODM/PHPCR/Tools/Console/Command/DocumentConvertTranslationCommand.php
lib/Doctrine/ODM/PHPCR/Tools/Helper/TranslationConverter.php
lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/AttributeTranslationStrategy.php
lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/ChildTranslationStrategy.php
lib/Doctrine/ODM/PHPCR/Translation/TranslationStrategy/NonTranslatedStrategy.php
tests/Doctrine/Tests/Models/Translation/ChildTranslationArticle.php
tests/Doctrine/Tests/Models/Translation/ChildTranslationComment.php
tests/Doctrine/Tests/Models/Translation/DatedComment.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/QueryBuilderTest.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/Tools/Helper/TranslationConverterTest.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/Translation/ChildTranslationStrategyTest.php
tests/Doctrine/Tests/ODM/PHPCR/Tools/Command/DocumentConvertTranslationCommandTest.php
tests/Doctrine/Tests/ODM/PHPCR/Tools/Command/DumpQueryBuilderReferenceCommandTest.php

fix https://github.com/symfony-cmf/CoreBundle/issues/164
doc PR: https://github.com/doctrine/phpcr-odm-documentation/pull/77

add a tool to convert translations

---

lib/Doctrine/ODM/PHPCR/Query/Builder/ConverterPhpcr.php
tests/Doctrine/Tests/Models/Blog/User.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/QueryBuilderTest.php

[Bug Fix] Make sure static literal value is properly cast to it's desired type

---

lib/Doctrine/ODM/PHPCR/Query/Builder/ConverterPhpcr.php

the good part from https://github.com/doctrine/phpcr-odm/pull/694

reuse cached $fieldMeta['property'] variable

---

.travis.yml
benchmarks/PersistBench.php
benchmarks/bootstrap.php
composer.json
phpbench.json.dist

Example PHPBench integration.
Can be useful as a base for checking for performance regressions.

Added PHPBench

---

phpbench.json.dist

Report column name changed in phpbench 0.12

Fixed PHPBench column name

---

CHANGELOG.md
lib/Doctrine/ODM/PHPCR/Decorator/DocumentManagerDecorator.php
lib/Doctrine/ODM/PHPCR/DocumentManager.php
lib/Doctrine/ODM/PHPCR/DocumentManagerInterface.php
tests/Doctrine/Tests/ODM/PHPCR/Decorator/DocumentManagerDecoratorTest.php
tests/Doctrine/Tests/ODM/PHPCR/DocumentManagerTest.php

implement getDocumentId

---

lib/Doctrine/ODM/PHPCR/UnitOfWork.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/ProxyTest.php

fix #743
show that 743 can not be reproduced.

test proxy awake behaviour

---

lib/Doctrine/ODM/PHPCR/Document/Generic.php

fix type hinting on collections

---

lib/Doctrine/ODM/PHPCR/Query/Builder/AbstractNode.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintChild.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConstraintOrx.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConverterBase.php
lib/Doctrine/ODM/PHPCR/Query/Builder/ConverterPhpcr.php
lib/Doctrine/ODM/PHPCR/Query/Builder/OperandDynamicFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/OperandFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/OrderBy.php
lib/Doctrine/ODM/PHPCR/Query/Builder/QueryBuilder.php
lib/Doctrine/ODM/PHPCR/Query/Builder/Select.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceFactory.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceJoinConditionDescendant.php
lib/Doctrine/ODM/PHPCR/Query/Builder/SourceJoinConditionFactory.php
lib/Doctrine/ODM/PHPCR/Tools/Console/Command/DumpQueryBuilderReferenceCommand.php

this is mainly for the generated reference page in the phpcr-odm-documentation

cleanup query builder documentation

---

.travis.yml
composer.json

Added Symfony 4 support. 
#SymfonyConHackday2017

Symfony 4 support

---

tests/Doctrine/Tests/ODM/PHPCR/Functional/DocumentRepositoryTest.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/PropertyTest.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/Translation/ChildTranslationStrategyTest.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/Versioning/AnnotationsTest.php
tests/Doctrine/Tests/ODM/PHPCR/Mapping/ClassMetadataTest.php

I've refactored some tests with [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue) and [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull) methods.

Refactoring tests

---

.travis.yml
composer.json

basically b8f750a6706fb4e5aed9db266db9d02d177f6a68

backport symfony 4.0 support to the 1.4 branch

---

.styleci.yml
lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadata.php
lib/Doctrine/ODM/PHPCR/Mapping/Driver/XmlDriver.php
lib/Doctrine/ODM/PHPCR/UnitOfWork.php

`isset` allow us to pass multiple values to check.
[PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me on that.
Also enabled in [`StyleCI`](https://styleci.readme.io/docs/fixers#section-combine_consecutive_issets).

Combine consecutives issets

---

lib/Doctrine/ODM/PHPCR/UnitOfWork.php
tests/Doctrine/Tests/ODM/PHPCR/Functional/ReorderTest.php

Fix issue when comparing nodes with integer names

---

lib/Doctrine/ODM/PHPCR/Tools/Console/MetadataFilter.php

https://github.com/doctrine/orm/pull/5715#issuecomment-196767852
I have no clue how to adapt the tests though

Apply doctrine/orm#5715 Fix MetadataFilter regression
